### ISSUE TITLE
push_signals_df failing with AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by rob-yerc** [amphoradata/python-sdk#23] opened 2020-11-13 02:58 UTC
Here is the data:
Building dataframe with WaterQuality data for:  big1 (e564226d-709f-4fbb-bfc0-16bd44ea676d)
   nitrate  nitrite  orthophosphate  totalnitrogen  totalphosphorus  wqph  wqtemperature                   t
0    0.500    0.000           0.180            0.1            0.433  7.61           43.0 2020-06-10 11:26:43
1    0.400    0.000           0.180            3.0            0.770  8.29           49.0 2020-06-29 11:30:08
2    0.600    0.001           0.260            1.5            0.570  8.19           50.0 2020-07-10 09:59:22
3    0.900    0.180           0.500            1.6            0.000  8.45           55.0 2020-07-22 10:04:15
4    0.800    0.001           0.290            0.0            0.200  8.34           58.0 2020-08-05 11:59:27
5    0.633    0.000           0.277            0.0            0.447  8.31           51.0 2020-08-25 10:40:13
6    0.600    0.000           0.290            1.7            0.450  8.57           53.0 2020-09-16 11:22:04

AttributeError: 'list' object has no attribute 'items'
---------------------------------------------------------------------------
~/gitlab/dataingress/.venv/lib64/python3.9/site-packages/amphora/amphora.py in push_signals_df(self, df, auto)
    210                         df[column_name].iloc[0])
    211                     self.create_signal(df[column_name].name, value_type)
--> 212         pusher.push(df)
    213 
    214     def push_signals_dict_array(self, dictionaries: [dict]):
~/gitlab/dataingress/.venv/lib64/python3.9/site-packages/amphora/amphora_signal_pusher.py in push(self, df)
     16     def push(self, df: pd.DataFrame = None):
     17         dictionaries = df.to_dict(orient='records')
---> 18         self.push_signals_dictionaries(dictionaries)
     19 
     20     def push_signals_dictionaries(self, dictionaries: [dict]):
~/gitlab/dataingress/.venv/lib64/python3.9/site-packages/amphora/amphora_signal_pusher.py in push_signals_dictionaries(self, dictionaries)
     23             validate_dictionary(signals, d)
     24 
---> 25         self.amphoraeApi.amphorae_signals_upload_signal_batch2(
     26             self._id, dictionaries)
     27 
~/gitlab/dataingress/.venv/lib64/python3.9/site-packages/amphora_api_client/api/amphorae_api.py in amphorae_signals_upload_signal_batch2(self, id, request_body, **kwargs)
   3207         """
   3208         kwargs['_return_http_data_only'] = True
-> 3209         return self.amphorae_signals_upload_signal_batch2_with_http_info(
   3210             id, request_body, **kwargs)  # noqa: E501
   3211 
~/gitlab/dataingress/.venv/lib64/python3.9/site-packages/amphora_api_client/api/amphorae_api.py in amphorae_signals_upload_signal_batch2_with_http_info(self, id, request_body, **kwargs)
   3287         auth_settings = ['Bearer']  # noqa: E501
   3288 
-> 3289         return self.api_client.call_api(
   3290             '/api/amphorae/{id}/batchSignalValues',
   3291             'POST',
~/gitlab/dataingress/.venv/lib64/python3.9/site-packages/amphora_api_client/api_client.py in call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, async_req, _return_http_data_only, collection_formats, _preload_content, _request_timeout, _host)
    371         """
    372         if not async_req:
--> 373             return self.__call_api(resource_path, method, path_params,
    374                                    query_params, header_params, body,
    375                                    post_params, files, response_type,
~/gitlab/dataingress/.venv/lib64/python3.9/site-packages/amphora_api_client/api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, _return_http_data_only, collection_formats, _preload_content, _request_timeout, _host)
    196             # deserialize response data
    197             if response_type:
--> 198                 return_data = self.deserialize(response_data, response_type)
    199             else:
    200                 return_data = None
~/gitlab/dataingress/.venv/lib64/python3.9/site-packages/amphora_api_client/api_client.py in deserialize(self, response, response_type)
    273             data = response.data
    274 
--> 275         return self.__deserialize(data, response_type)
    276 
    277     def __deserialize(self, data, klass):
~/gitlab/dataingress/.venv/lib64/python3.9/site-packages/amphora_api_client/api_client.py in __deserialize(self, data, klass)
    297                 return {
    298                     k: self.__deserialize(v, sub_kls)
--> 299                     for k, v in six.iteritems(data)
    300                 }
    301 
~/gitlab/dataingress/.venv/lib64/python3.9/site-packages/six.py in iteritems(d, **kw)
    587 
    588     def iteritems(d, **kw):
--> 589         return iter(d.items(**kw))
    590 
    591     def iterlists(d, **kw):
AttributeError: 'list' object has no attribute 'items'

**Comment by xtellurian** [comment] 2020-11-13 05:19
I reproduced the error, it's definitely a bug.

The signal data get's uploaded correctly, but the response isn't deserialised properly. It looks like the API documentation is slightly incorrect - the API returns an array of dictionaries - not just a single dictionary.

**Comment by xtellurian** [comment] 2020-11-13 05:26
Should be resolved in 0.10.28

**Comment by xtellurian** [comment] 2020-11-15 23:32
@rob-yerc I've pushed a new version `0.10.28-dev1`.

has that resolved the error?

**Comment by rob-yerc** [comment] 2020-11-16 15:11
Yes, the push_signals_df is working as expected with 0.10.28.dev1  Unfortunately, issue #20 Getting unexpected keyword argument 'kind' when pulling signals is back.

**Comment by xtellurian** [comment] 2020-11-16 22:40
Re-opened #20

**Closed as completed by xtellurian** 2020-11-16 22:40 UTC
Labels: bug
